// <auto-generated />
using System;
using Infrastructure.Data.Persistent;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424104433_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Domain.Entities.MedicineRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Given")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("MedicineRecord");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0684cf2-f249-41f6-af83-0a75e0a5e7d3"),
                            Given = true,
                            MedicineName = "Atenolol",
                            ResidentId = new Guid("694b9796-dc5a-4a68-bafb-0a59595e8fb3"),
                            Timestamp = new DateTime(2026, 4, 1, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c9f94fc6-c542-4ae9-ade6-3c40cd2262d8"),
                            Given = true,
                            MedicineName = "Sertraline",
                            ResidentId = new Guid("694b9796-dc5a-4a68-bafb-0a59595e8fb3"),
                            Timestamp = new DateTime(2026, 4, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4bbd018f-b297-4973-85e9-5be5b0499834"),
                            Given = false,
                            MedicineName = "Bisoprolol",
                            ResidentId = new Guid("d3e4f5a6-7890-1234-5678-9abcdef01234"),
                            Timestamp = new DateTime(2026, 4, 2, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c9f58ba2-c394-4f8c-b058-c13766689c79"),
                            Given = false,
                            MedicineName = "Quetiapine",
                            ResidentId = new Guid("f5a6b7c8-9012-3456-789a-bcdef0123456"),
                            Timestamp = new DateTime(2026, 4, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Entities.MedicineStatusView", b =>
                {
                    b.Property<int>("ActiveMedicines")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.ToTable((string)null);

                    b.ToView("medicinestatusview", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PainkillerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("GivenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NextAllowedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("PainkillerRecord");
                });

            modelBuilder.Entity("Domain.Entities.PainkillerStatusView", b =>
                {
                    b.Property<int>("ActivePainkillers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.ToTable((string)null);

                    b.ToView("painkillerstatusview", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PhoneAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CaregiverId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PhoneAssignments");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.Resident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<int>("TrafficLightStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Residents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("694b9796-dc5a-4a68-bafb-0a59595e8fb3"),
                            Initials = "A",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-1234-56789abcdef0"),
                            Initials = "B",
                            TrafficLightStatus = 2
                        },
                        new
                        {
                            Id = new Guid("c2d3e4f5-6789-0123-4567-89abcdef0123"),
                            Initials = "C",
                            TrafficLightStatus = 1
                        },
                        new
                        {
                            Id = new Guid("d3e4f5a6-7890-1234-5678-9abcdef01234"),
                            Initials = "D",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e4f5a6b7-8901-2345-6789-abcdef012345"),
                            Initials = "E",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("f5a6b7c8-9012-3456-789a-bcdef0123456"),
                            Initials = "F",
                            TrafficLightStatus = 1
                        },
                        new
                        {
                            Id = new Guid("a6b7c8d9-0123-4567-89ab-cdef01234567"),
                            Initials = "GA",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("b7c8d9e0-1234-5678-9abc-def012345678"),
                            Initials = "H",
                            TrafficLightStatus = 2
                        },
                        new
                        {
                            Id = new Guid("c8d9e0f1-2345-6789-abcd-ef0123456789"),
                            Initials = "I",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("d9e0f1a2-3456-789a-bcde-f01234567890"),
                            Initials = "J",
                            TrafficLightStatus = 0
                        },
                        new
                        {
                            Id = new Guid("e0f1a2b3-4567-89ab-cdef-012345678901"),
                            Initials = "K",
                            TrafficLightStatus = 2
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-5678-9abc-def0-123456789012"),
                            Initials = "GB",
                            TrafficLightStatus = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.ResidentNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ResidentId");

                    b.ToTable("ResidentNotes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5a6b7c8-9012-3456-7890-abcdef012345"),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident A's note.",
                            ResidentId = new Guid("694b9796-dc5a-4a68-bafb-0a59595e8fb3")
                        },
                        new
                        {
                            Id = new Guid("a6b7c8d9-0123-4567-8901-bcdef0123456"),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident B's note.",
                            ResidentId = new Guid("a1b2c3d4-e5f6-7890-1234-56789abcdef0")
                        },
                        new
                        {
                            Id = new Guid("b7c8d9e0-1234-5678-9012-cdef01234567"),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident C's note.",
                            ResidentId = new Guid("c2d3e4f5-6789-0123-4567-89abcdef0123")
                        },
                        new
                        {
                            Id = new Guid("c8d9e0f1-2345-6789-0123-def012345678"),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident D's note.",
                            ResidentId = new Guid("d3e4f5a6-7890-1234-5678-9abcdef01234")
                        },
                        new
                        {
                            Id = new Guid("d9e0f1a2-3456-7890-1234-ef0123456789"),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident E's note.",
                            ResidentId = new Guid("e4f5a6b7-8901-2345-6789-abcdef012345")
                        },
                        new
                        {
                            Id = new Guid("e0f1a2b3-4567-8901-2345-f0123456789a"),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident F's note.",
                            ResidentId = new Guid("f5a6b7c8-9012-3456-789a-bcdef0123456")
                        },
                        new
                        {
                            Id = new Guid("f1a2b3c4-5678-9012-3456-0123456789ab"),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident GA's note.",
                            ResidentId = new Guid("a6b7c8d9-0123-4567-89ab-cdef01234567")
                        },
                        new
                        {
                            Id = new Guid("a2b3c4d5-6789-0123-4567-123456789abc"),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident H's note.",
                            ResidentId = new Guid("b7c8d9e0-1234-5678-9abc-def012345678")
                        },
                        new
                        {
                            Id = new Guid("b3c4d5e6-7890-1234-5678-23456789abcd"),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident I's note.",
                            ResidentId = new Guid("c8d9e0f1-2345-6789-abcd-ef0123456789")
                        },
                        new
                        {
                            Id = new Guid("c4d5e6f7-8901-2345-6789-3456789abcde"),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident J's note.",
                            ResidentId = new Guid("d9e0f1a2-3456-789a-bcde-f01234567890")
                        },
                        new
                        {
                            Id = new Guid("d5e6f7a8-9012-3456-7890-456789abcde0"),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident K's note.",
                            ResidentId = new Guid("e0f1a2b3-4567-89ab-cdef-012345678901")
                        },
                        new
                        {
                            Id = new Guid("e6f7a8b9-0123-4567-8901-56789abcde01"),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident GB's note.",
                            ResidentId = new Guid("f1a2b3c4-5678-9abc-def0-123456789012")
                        },
                        new
                        {
                            Id = new Guid("f7a8b9c0-1234-5678-9012-6789abcde012"),
                            EditedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Resident GB's note 2.",
                            ResidentId = new Guid("f1a2b3c4-5678-9abc-def0-123456789012")
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fabc2277-7992-491b-ae4a-bc78f8de56aa"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("d1c9e8b5-3f4a-4c2e-9a1b-5e6f7a8b9c0d"),
                            Name = "SuperUser",
                            NormalizedName = "SUPERUSER"
                        },
                        new
                        {
                            Id = new Guid("ee697c76-947a-4fe2-8b14-40194c30bdae"),
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "CanManageUsers",
                            RoleId = new Guid("fabc2277-7992-491b-ae4a-bc78f8de56aa")
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "CanManageMedicine",
                            RoleId = new Guid("fabc2277-7992-491b-ae4a-bc78f8de56aa")
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "CanViewMedicine",
                            RoleId = new Guid("ee697c76-947a-4fe2-8b14-40194c30bdae")
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "CanManageResidents",
                            RoleId = new Guid("ee697c76-947a-4fe2-8b14-40194c30bdae")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MedicineRecord", b =>
                {
                    b.HasOne("Domain.Entities.Resident", null)
                        .WithMany("Medicines")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.PainkillerRecord", b =>
                {
                    b.HasOne("Domain.Entities.Resident", null)
                        .WithMany("Painkillers")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ResidentNote", b =>
                {
                    b.HasOne("Domain.Entities.Resident", null)
                        .WithMany("Notes")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Resident", b =>
                {
                    b.Navigation("Medicines");

                    b.Navigation("Notes");

                    b.Navigation("Painkillers");
                });
#pragma warning restore 612, 618
        }
    }
}
