
services:
  slottets-sqlserver:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      vlan-db:
        ipv4_address: 10.29.10.10

      # vlan-app:

  build-stage:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DOTNET_RUNNING_IN_CONTAINER: true
    restart: "no"
    networks:
      vlan-db:
      # vlan-app:

  tests-stage:
    build:
      context: .
      dockerfile: Dockerfile
      target: tests-stage
    depends_on:
      slottets-sqlserver:
        condition: service_started
      build-stage:
        condition: service_completed_successfully
    working_dir: /workspace
    volumes:
      - ./TestResults:/artifacts/TestResults
    networks:
      vlan-db:
      # vlan-app:
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - ASPNETCORE_ENVIRONMENT=Production
      - DOCKER_DOTNET_TEST=true
    restart: "no"

  publish-stage:
    build:
      context: .
      dockerfile: Dockerfile
      target: publish-stage
    depends_on:
      tests-stage:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: no

  webapi-final-stage:
    build:
      context: .
      dockerfile: Dockerfile
      target: webapi-final-stage
    depends_on:
      publish-stage:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5025
    ports:
      - "5025:5025"
    expose:
      - 5025
    networks:
      vlan-web:
          ipv4_address: 10.29.30.11
    volumes:
      - ./DataProtection-Keys:/root/.aspnet/DataProtection-Keys
    restart: "always"

  webui-final-stage:
    build:
      context: .
      dockerfile: Dockerfile
      target: webui-final-stage
    depends_on:
      publish-stage:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5035
    ports:
      - "5035:5035"
    volumes:
      - ./src/WebUI/WebUI/DataProtection-Keys:/app/DataProtection-Keys
    networks:
      vlan-web:
          ipv4_address: 10.29.30.10
    restart: "always"

volumes:
  mysql_data:

networks:
  vlan-db:
    driver: bridge
    ipam:
      config:
        - subnet: 10.29.10.0/24
  vlan-web:
    driver: bridge
    ipam:
      config:
        - subnet: 10.29.30.0/24
