@Api_HostAddress = http://localhost:5051

### Identity Register user
POST {{Api_HostAddress}}/Account/register
Accept: application/json
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "Password123!"
}

### Identity Login
POST {{Api_HostAddress}}/Account/login
Accept: application/json
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "Password123!"
}

### Identity Refresh token
POST {{Api_HostAddress}}/Account/refresh
Accept: application/json
Content-Type: application/json

{
    "accessToken": "PASTE_ACCESS_TOKEN_HERE",
    "refreshToken": "PASTE_REFRESH_TOKEN_HERE"
}

### Identity Logout
POST {{Api_HostAddress}}/Account/logout
Accept: application/json
Authorization: Bearer PASTE_ACCESS_TOKEN_HERE

### Identity delete user
DELETE {{Api_HostAddress}}/Account/delete
Accept: application/json
Authorization: Bearer PASTE_ACCESS_TOKEN_HERE

### Database is connected
GET {{Api_HostAddress}}/DatabaseHealthCheck/IsDbConnected
Accept: application/json
