#!/bin/bash
set -euo pipefail

framework="net8.0"

#export NUGET_PACKAGES=/root/.nuget/packages

# Create a timestamped results dir that can be mounted from host
timestamp=$(date -u +%Y%m%dT%H%M%SZ)
resultDir="/artifacts/TestResults/$timestamp"
coverageDir="/artifacts/TestResults/CoverageReport/$timestamp"
latestCoverageDir="/artifacts/TestResults/CoverageReport/Latest"

mkdir -p "${resultDir}"
mkdir -p "${coverageDir}/Markdown" "${coverageDir}/Html" "${coverageDir}/Cobertura" "${coverageDir}/Badges"

# clean up old results (keep last 5)
ls -1dt /artifacts/TestResults/*/ | tail -n +6 | xargs rm -rf

# Clean Latest coverage report
rm -rf "${latestCoverageDir}"

# Configuration (allow override from environment)
CONFIGURATION=${CONFIGURATION:-Development}

# Ensure we're in workspace containing the solution/repo
cd /workspace || exit 1

# Ensure tests use Development environment
export ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}

exit_code=0

echo "Restoring and building solution..."
dotnet restore || exit_code=$?
dotnet build -c Debug --no-restore || exit_code=$?


echo "Update databses for tests..."
#dotnet ef database update --project src/Infrastructure/Infrastructure.csproj --startup-project src/Infrastructure --configuration Debug || true

echo "Discovering test projects..."
#dotnet clean
#dotnet nuget locals all --clear

if [ $exit_code -ne 0 ]; then
  echo "Build failed with exit code $exit_code"
  exit $exit_code
fi

# Check if .runsettings exists before running tests
if [ ! -f .runsettings ]; then
  echo ".runsettings file not found in $(pwd). Aborting tests."
  exit 1
fi

dotnet test -c Debug --results-directory "${resultDir}" --collect:"XPlat Code Coverage" --logger "trx" --settings .runsettings || exit_code=$?

if [ $exit_code -ne 0 ]; then
  echo "Some tests failed with exit code $exit_code"
  exit $exit_code
fi

# After running tests try to merge coverage reports into a single file and generate an HTML report
echo "Combining coverage reports (results in: ${resultDir})..."

if [ -d "${resultDir}" ]; then
  # Find all coverage.cobertura.xml files generated by dotnet test
  mapfile -t coverage_files < <(find "${resultDir}" -type f -name "coverage.cobertura.xml")

  if [ "${#coverage_files[@]}" -gt 0 ]; then
    echo "Found coverage files. Generating combined report..."

    rm -rf "${latestCoverageDir}"

    # Generate HTML and Cobertura combined report
    reportgenerator -reports:"${resultDir}/**/coverage.cobertura.xml" -targetdir:"${latestCoverageDir}" -reporttypes:"Cobertura" -title:"Slottests CareManagement - coverage report" || echo "reportgenerator failed"
    reportgenerator -reports:"${resultDir}/**/coverage.cobertura.xml" -targetdir:"${latestCoverageDir}/Html" -reporttypes:"Html_Dark" -title:"Slottests Care - coverage report" || echo "reportgenerator failed"
    reportgenerator -reports:"${resultDir}/**/coverage.cobertura.xml" -targetdir:"${latestCoverageDir}/Markdown" -reporttypes:"Markdown" -title:"Slottests Care - coverage report" || echo "reportgenerator failed"
    reportgenerator -reports:"${resultDir}/**/coverage.cobertura.xml" -targetdir:"${latestCoverageDir}/Badges" -reporttypes:"Badges" -title:"Slottests Care - coverage report" || echo "reportgenerator failed"
  else
    echo "No coverage files found in ${resultDir}"
  fi
else
  echo "Test results directory ${resultDir} does not exist. No coverage files to process."
fi

echo "Test results and coverage reports are available in /artifacts/TestResults/"

exit $exit_code
#tail -f /dev/null # Keep container running for inspection
