name: Build and Test
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name : Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env
      - name: Copy .env file to API project
        run: cp .env src/Api/.env
      - name: Load .env file
        run: export $(cat .env | xargs)
      - name: Restore dependencies
        run: dotnet restore Slottet.CareManagement.sln
      - name: Build
        run: dotnet build --no-restore Slottet.CareManagement.sln
      - name: Test
        run: dotnet test --no-build --verbosity normal --solution Slottet.CareManagement.sln
