name: Build and Test
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
jobs:
  BuildSecrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check for ENV_FILE secret
        run: |
          if [ -z "${{ secrets.ENV_FILE }}" ]; then
            echo "Error: ENV_FILE secret is not set."
            exit 1
          fi
      - name: Create .env file
        run: |
          printf '%b' "${{ secrets.ENV_FILE }}" > .env
      - name: Debug .env file
           run: cat .env
      - name: Upload .env file as artifact
        uses: actions/upload-artifact@v7
        with:
          name: env-file
          path: .env

  build:
    needs: BuildSecrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name : Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x
      - name: Download .env file artifact
        uses: actions/download-artifact@v8
        with:
          name: env-file
      - name: Copy .env file to API project
        run: cp .env src/Api/.env
      - name: Load .env file
        run: export $(cat .env | xargs)
      - name: Restore dependencies
        run: dotnet restore Slottet.CareManagement.sln
      - name: Build
        run: dotnet build --no-restore Slottet.CareManagement.sln
      - name: Test
        run: dotnet test --no-build --verbosity normal --solution Slottet.CareManagement.sln
