name: Build and Test
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
jobs:
  BuildSecrets:
    runs-on: ubuntu-latest
    environment: database
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "ConnectionStrings__AppDbContext=Server=${{ secrets.MYSQL_HOST }};Port=3307;Database=${{ secrets.MYSQL_DATABASE }};User=${{ secrets.MYSQL_USER }};Password=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "TokenValidationParameters__IssuerSigningKey=bZcurjVyDJCm2%KHwwRcduIOyjeKyR22" >> .env
      - name: Upload .env file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: .env
      
  build:
    runs-on: ubuntu-latest
    environment: Database
    steps:
      - uses: actions/checkout@v4
      - name : Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env
      - name: Copy .env file to API project
        run: cp .env src/Api/.env
      - name: Load .env file
        run: export $(cat .env | xargs)
      - name: Restore dependencies
        run: dotnet restore Slottet.CareManagement.sln
      - name: Build
        run: dotnet build --no-restore Slottet.CareManagement.sln
      - name: Test
        run: dotnet test --no-build --verbosity normal --solution Slottet.CareManagement.sln
